#Experiment 8
### Name: Tannishtha Gupta
### PRN: 25070123049
### Class: ENTC A3
#### Title: Tools of EDA- Study of NumPy library

In [19]:
# declaration of Numpy
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.array([[1,2,3] , [4,5,6]])
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [20]:
# dimension of array
print(a.ndim)
print(b.ndim)

1
2


In [4]:
a.shape

(4,)

In [21]:
b.shape

(2, 3)

In [22]:
# for data type
a.dtype
b.dtype

dtype('int64')

In [9]:
# inbuilt functions using numpy
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
print(b*2)
print(a+5)

[[ 2  4  6]
 [ 8 10 12]]
[15 25 35 45]


In [26]:
a+5

array([15, 25, 35, 45])

In [28]:
np.mean(a)

np.float64(25.0)

In [29]:
np.median(a)

np.float64(25.0)

In [30]:
b+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
np.mean(b)

np.float64(3.5)

In [32]:
np.median(b)

np.float64(3.5)

In [41]:
np.sum(a)

np.int64(100)

In [36]:
np.sum(b)

np.int64(21)

In [40]:
np.min(a)

np.int64(10)

In [39]:
np.min(b)

np.int64(1)

In [43]:
np.max(a)

np.int64(40)

In [44]:
np.max(b)

np.int64(6)